aloha/urls.py
from django.conf.urls import patterns, url, include
from aloha import views

urlpatterns = patterns('',
    url(r'^$',
        views.index, 
        name='index'),
    url(r'create_user/$',
        views.create_user,
        name='create_user'),
    url(r'dashboard/$',
        views.dashboard,
        name='dashboard'),
    url(r'get_key/$',
        views.get_key,
        name='get_key'),
    url(r'login_page/$',
        views.login_page,
        name='login_page'),
    url(r'logout_page/$',
        views.logout_page,
        name='logout_page'),
    url(r'privacy/$',
        views.privacy,
        name='privacy'),
    url(r'register/$',
        views.register,
        name='register'),
    url(r'sandbox/$',
        views.sandbox,
        name='sandbox'),
    url(r'tos/$',
        views.tos,
        name='tos'),
)

auth_wrapper/urls.py
from django.conf.urls import patterns, include, url
from django.views import generic
from django.http import HttpResponseRedirect


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', lambda x: HttpResponseRedirect('/vcb/')),
    # url(r'^video_search/', include('video_search.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('aloha.urls', namespace='aloha')),
    # url(r'^vcb/', include('vcb.urls', namespace="vcb")),
)

aloha/views.py
import json
import logging
import pdb

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.shortcuts import render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test

from .aloha_utils import *

from bs4 import BeautifulSoup

# TODO: add in email verification for registration:
# http://stackoverflow.com/questions/5495317/implementation-of-e-mail-verification-in-django
# http://stackoverflow.com/questions/1325983/django-send-email-in-html-with-django-registration

def create_user(request):
    if request.method == 'POST':
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        passwd = request.POST['passwd']

        if not User.objects.filter(email = email).exists():
            user = User.objects.create_user(email, email, passwd)
            user.is_active = True
            if not fname:
                user.first_name = email.split('@')[0]
            else:
                user.first_name = fname
            user.last_name = lname
            user.save()
            user = authenticate(username=email, password=passwd)
            login(request, user)
            return HttpResponseRedirect(reverse('aloha:dashboard'))
        else:
            return render(request, 'aloha/register.html',
                    {'error' : 'E-mail already exists. Please try again.'})
    return HttpResponseRedirect(reverse('aloha:register'))

@login_required
@user_passes_test(lambda u: u.is_active)
def dashboard(request):
    """
    User dashboard to edit books?
    """
    return render(request, 'aloha/dashboard.html')

@login_required
@user_passes_test(lambda u: u.is_active)
def get_key(request):
    key = ''
    host = request.GET['host']
    try:
        key = request_key_from_handcar(request.user, host)
    except Exception as ex:
        log_error('views.get_key()', ex)
    finally:
        return HttpResponse(key)

def index(request):
    redirect = request.GET.get('next')
    if not redirect:
        redirect = reverse('aloha:dashboard')
    return render(request, 'aloha/index.html', {
        'next':redirect,})

def login_page(request):
    """
    Log in users, according to
    https://docs.djangoproject.com/en/dev/topics/auth/default/#auth-web-requests
    """
    username = request.POST['email']
    password = request.POST['passwd']
    redirect_url = request.POST['next']
    user = authenticate(username = username, password = password)
    if user is not None:
        if user.is_active:
            login(request, user)
            return HttpResponseRedirect(redirect_url)
        else:
            state = "Your account is not active."
    else:
        state = "Incorrect username and/or password."
    return render(request, 'aloha/index.html', {
        'state' : state, 'next': redirect_url})

def logout_page(request):
    """
    Log users out and re-direct them back to index
     """
    logout(request)
    return HttpResponseRedirect(reverse('aloha:index'))

def privacy(request):
    """
    Redirect to the site's Privacy Policy
    """
    return render(request, 'aloha/privacy.html')

def register(request):
    """
    To render the register page
    """
    return render(request, 'aloha/register.html')

@login_required
@user_passes_test(lambda u: u.is_active)
def sandbox(request):
    with open(settings.PROJECT_PATH + '/../templates/sandbox/index.html') as f:
        page = BeautifulSoup(f)
        return HttpResponse(page.html)
    # return render(request, 'sandbox/index.html')

def tos(request):
    """
    Redirect to the site's Terms of Service
    """
    return render(request, 'aloha/tos.html')

templates/aloha/base.html
<!DOCTYPE html>
<html lang='en' xmlns="http://www.w3.org/1999/xhtml">
<!--
Thank you to the other open-source software packages used.
Apologies for any I accidentally missed - please let me know and I can update this list:
  - Bootstrap
  - jQuery
  - jQuery UI
  - Django
  - Python
  - Bootbox
  - Selenium
  - jQuery BlockUI
  - Font Awesome
-->
<head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Authenticated MC3 Aloha Editor">
    <meta name="author" content="MIT OEIT">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

    {% load i18n %}
    {% load static %}

    <link rel="stylesheet" href="{{STATIC_URL}}css/bootstrap.css" />
    <link rel="stylesheet" href="{{STATIC_URL}}css/bootstrap-theme.min.css" />
    <link rel="stylesheet" href="{{STATIC_URL}}css/jquery-ui-1.10.4.custom.css" />
    <link rel="stylesheet" href="{{STATIC_URL}}css/font-awesome.css" />
    <link rel="stylesheet" href="{{STATIC_URL}}css/mc3.css" />
    <link rel="stylesheet" href="{{STATIC_URL}}css/aloha_wrapper.css" />

    {% block head_scripts %}{% endblock %}
</head>
<body>
    <div class="body_wrapper">
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="navbar-header pull-left">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">MC3 Aloha</a>
            </div>
{#            <div>#}
                {% block user_toggle %} {% endblock %}
{#            </div>#}
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    {% block menu %} {% endblock %}
                </ul>
            </div>
        </div>
        {% block content %} {% endblock %}

        <div id="footer" class="container">
            <div class="row">
                  <p class="text-center">Application development and website support provided by
                      the <a href="http://oeit.mit.edu">MIT Office of Educational Innovation and Technology (OEIT)</a>.</p>
                  <p class="copyright">&copy; <a href="http://oeit.mit.edu" target="_blank">MIT OEIT</a> 2014</p>
            </div>
        </div>
    </div>

     <script type="text/javascript" src="{{STATIC_URL}}js/lib/jquery-1.7.1.min.js"></script>
{#    <script type="text/javascript" src="{{STATIC_URL}}js/lib/jquery-2.0.3.js"></script>#}
{#    <script type="text/javascript" src="{{STATIC_URL}}js/lib/jquery-ui-1.10.4.js"></script>#}

    <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="{{STATIC_URL}}js/lib/html5.shim.js"></script>
    <![endif]-->
    {% block extra_scripts %} {% endblock %}
</body>
</html>

templates/aloha/base_menu.html
{% extends 'aloha/base.html' %}

{% block menu %}
    <li class="active">
        <a href="{% url 'aloha:dashboard' %}">
            <i class="fa fa-dashboard"></i>
            Dashboard
        </a>
    </li>
    <li>
        <div class="mc3_selector">
            <select id="host_selector" class="">
                <option value="oki-dev.mit.edu">
                    <span class="hidden-tablet"> OKI-DEV</span>
                </option>
                <option value="mc3-demo.mit.edu">
                    <span class="hidden-tablet"> MC3 Demo</span>
                </option>
                <option value="mc3.mit.edu">
                    <span class="hidden-tablet"> MC3</span>
                </option>
            </select>
        </div>
    </li>
    <li>
        <div class="mc3_selector">
            <input type="hidden" value="" id="bank_selector" class=""/>
        </div>
    </li>
{% endblock %}

{% block data_script %}
    <script src="{{ STATIC_URL }}js/lib/jquery.blockui.js"></script>
    <script src="{{ STATIC_URL }}js/lib/csrf.js"></script>
{% endblock %}

templates/aloha/dashboard.html
{% extends 'aloha/base_menu.html' %}

{% block title %}MC3 Aloha Editor - Dashboard{% endblock %}

{% block head_scripts %}
    <link rel="stylesheet" href="{{STATIC_URL}}css/aloha.css" />
    <link rel="stylesheet" href="{{STATIC_URL}}css/html5_metacontent.css" />
    <link rel="stylesheet" href="{{STATIC_URL}}css/html5_content_in_oerpub.css" />
    <link rel="stylesheet" href="{{STATIC_URL}}css/style.css" />
    <link rel="stylesheet" href="{{STATIC_URL}}css/toolbar.css" />
    <link rel="stylesheet" href="{{STATIC_URL}}css/select2.css" />
{% endblock %}

{% block user_toggle %}
    <div class="navbar-header pull-right user_menu" >
        <button class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="user_toggle">
            <i class="fa fa-gears"></i>
            <span class="hidden-xs"> {{ request.user.first_name }}</span>
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="user_toggle">
            <li><a href="profile/">
                <i class="fa fa-user"></i>
                <span class="hidden-xs"> Profile</span>
            </a></li>
            <li><a class="nav-help" href="#">
                <i class="fa fa-info-circle"></i>
                <span class="hidden-xs"> Help</span>
            </a></li>
            <li class="divider"></li>
            <li><a href="logout_page/" class="logout">
                <i class="fa fa-external-link"></i>
                <span class="hidden-xs"> Logout</span>
            </a></li>
            {% if user.is_staff %}
                <li class="divider"></li>
                <li class="nav-header hidden-xs">Administrative</li>
                <li><a class="nav-admin" href="#">
                    <i class="fa fa-cog"></i>
                    <span class="hidden-xs"> Create / Modify Classes</span>
                </a></li>
            {% endif %}
        </ul>
    </div>
    <!-- user dropdown ends -->
{% endblock %}

{% block content %}
    <div id="ie6-container-wrap">
        <div id="container">
            <!-- ================= -->
            <!--  Toolbar Buttons  -->
            <!-- ================= -->
            <div class="toolbar aloha-dialog">
                <div class="btn-toolbar" role="toolbar">
                  <div class="btn-group">
                    <button class="btn btn-default action save" rel="tooltip" title="Save">Save</button>
                  </div>
                  <div class="btn-group">
                    <button class="btn btn-default action undo" rel="tooltip" title="Undo"><i class="fa fa-undo"></i></button>
                    <button class="btn btn-default action redo" rel="tooltip" title="Redo"><i class="fa fa-rotate-right"></i></button>
                  </div>
                  <div class="btn-group headings">
                    <button class="btn btn-default heading dropdown-toggle" data-toggle="dropdown" rel="tooltip" title="Text Heading" id="headingbutton">
                      <span class="currentHeading">&nbsp;</span>
                      <span class="caret"></span></button>
                    <ul class="dropdown-menu"></ul>
                  </div>
                  <div class="btn-group">
                    <button class="btn btn-default action strong" rel="tooltip" title="Bold"><i class="fa fa-bold"></i></button>
                    <button class="btn btn-default action emphasis" rel="tooltip" title="Italics"><i class="fa fa-italic"></i></button>
                    <button class="btn btn-default action underline" rel="tooltip" title="Underline"><i class="fa fa-underline"></i></button>
                    <button class="btn btn-default action superscript" rel="tooltip" title="Superscript"><i class="fa fa-superscript"></i></button>
                    <button class="btn btn-default action subscript" rel="tooltip" title="Subscript"><i class="fa fa-subscript"></i></button>
                  </div>
                  <div class="btn-group">
                    <button class="btn btn-default action insertLink" rel="tooltip" title="Insert Link"><i class="fa fa-link"></i></button>
                    <!-- <button class="btn action changeHeading" data-tagname="pre" rel="tooltip" title="Code">Code</button> -->
                  </div>
                  <div class="btn-group">
                    <button class="btn btn-default action unorderedList" rel="tooltip" title="Insert Unordered List"><i class="fa fa-list-ul"></i></button>
                    <button class="btn btn-default action orderedList" rel="tooltip" title="Insert Ordered List"><i class="fa fa-list-ol"></i></button>
                    <button class="btn btn-default action indentList" rel="tooltip" title="Indent list item (move right)"><i class="fa fa-indent"></i></button>
                    <button class="btn btn-default action outdentList" rel="tooltip" title="Unindent list item (move left)"><i class="fa fa-outdent"></i></button>
                  </div>
                  <div class="btn-group">
                    <button class="btn btn-default action insertImage-oer" rel="tooltip" title="Insert Image"><i class="fa fa-picture-o"></i></button>
                    <!--<button class="btn action insertVideo-oer" rel="tooltip" title="Insert Video"><i class="icon-image-insert"></i></button>-->
                    <button class="btn btn-default action createTable" rel="tooltip" title="Create Table"><i class="fa fa-table"></i></button>
                    <button class="btn btn-default dropdown-toggle" data-toggle="dropdown" rel="tooltip" title="Table Operations">
                      <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                      <li><a href="#" class="action addrowbefore">Add Row Before</a></li>
                      <li><a href="#" class="action addrowafter">Add Row After</a></li>
                      <li><a href="#" class="action addcolumnbefore">Add Column Before</a></li>
                      <li><a href="#" class="action addcolumnafter">Add Column After</a></li>
                      <li><a href="#" class="action addheaderrow">Add Header Row</a></li>
                      <li><a href="#" class="action deleterow">Delete Row</a></li>
                      <li><a href="#" class="action deletecolumn">Delete Column</a></li>
                      <li><a href="#" class="action deletetable">Delete Table</a></li>
                    </ul>
                    <button class="btn btn-default action insertMath" rel="tooltip" title="Insert Math"><i class="fa fa-plus"></i></button>
                  </div>
                  <div class="btn-group">
                    <button class="btn btn-default btn-text dropdown-toggle" data-toggle="dropdown" rel="tooltip" title="Add a new...">
                      Add a new...
                      <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                      <li><a href="#" class="action insertNote">Note to Reader</a></li>
                      <li><a href="#" class="action insertExample">Example</a></li>
                      <li><a href="#" class="action insertExercise">Exercise</a></li>
                      <li><a href="#" class="action insertQuotation">Quotation</a></li>
                      <li><a href="#" class="action insertEquation">Equation</a></li>
                      <li><a href="#" class="action insertMC3Definition">MC3 Outcome</a></li>
                      <li><a href="#" class="action insertMC3Activity">MC3 Activity</a></li>
                    </ul>
                  </div>
                  <div class="btn-group">
                    <button class="btn btn-default action paste" rel="tooltip" title="paste">Paste</button>
                  </div>
                  <div class="btn-group">
                    <button class="btn btn-default action insertOEA" rel="tooltip" title="oea">OEA</button>
                  </div>
                </div>

                <div style="margin-top: 20px; width: 200px;">
                    <h4>Drag to add a new ...</h4>

                    <div class="semantic-drag-source">
                        <div class="note">
                            <div class="title"></div>
                        </div>

                        <div class="exercise">
                            <div class="problem"></div>
                        </div>

                        <div class="quote">
                        </div>

                        <div class="equation">
                        </div>

                        <dl class="mc3definition">
                        </dl>

                        <div class="mc3activity">
                            <div class="title"></div>
                        </div>
                    </div>

                </div>
            </div><!-- / ".toolbar" -->

            <div id="content">
                <div id="artboard">
                    <div id="statusmessage"></div>
                    <div id="editor">
                        <div id="canvas" class="aloha-root-editable" style="margin-left: 200px;"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_scripts %}
    <script type="text/javascript" src="{{STATIC_URL}}js/lib/jquery.center.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/lib/require.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/lib/bootstrap.2.2.2.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/lib/jquery-ui-1.9.0.custom-aloha.js"></script>
    <script type="text/javascript"
        src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_HTMLorMML-full&amp;delayStartupUntil=configured">
    </script>

    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
            jax: ["input/MathML", "input/TeX", "input/AsciiMath", "output/NativeMML", "output/HTML-CSS"],
            extensions: ["asciimath2jax.js","tex2jax.js","mml2jax.js","MathMenu.js","MathZoom.js","MathEvents.js","toMathML.js"],
            tex2jax: { inlineMath: [["[TEX_START]","[TEX_END]"], ["\\(", "\\)"]] },
            // Apparently we can't change the escape sequence for ASCIIMath (MathJax doesn't find it)
            // asciimath2jax: { inlineMath: [["[ASCIIMATH_START]", "[ASCIIMATH_END]"]], },

            TeX: {
            extensions: ["AMSmath.js","AMSsymbols.js","noErrors.js","noUndefined.js"], noErrors: { disabled: true }
            },
            AsciiMath: { noErrors: { disabled: true } }
        });
    </script>
    <script type="text/javascript" src="{{STATIC_URL}}js/lib/aloha-settings.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/lib/aloha.js"
        data-aloha-plugins="common/ui,
                            oer/copy,
                            oer/toolbar,
                            oer/overlay,
                            oer/format,
                            common/contenthandler,
                            common/paste,
                            common/block,
                            common/list,
                            oer/table,
                            oer/math,
                            oer/mathcheatsheet,
                            extra/draganddropfiles,
                            common/image,
                            oer/assorted,
                            oer/title,
                            common/undo,
                            oer/undobutton,
                            oer/genericbutton,
                            oer/semanticblock,
                            oer/exercise,
                            oer/quotation,
                            oer/equation,
                            oer/note,
                            mc3/mc3definition,
                            mc3/mc3activity,
                            mc3/oea">
    </script>
    <script type="text/javascript">
        var body_url = '{% url 'aloha:sandbox' %}';
        var save_url = null;
    </script>
    <script type="text/javascript" src="{{STATIC_URL}}js/lib/select2.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/controllers/mc3_auth_utils.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/controllers/dashboard.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/bindings/dashboard.js"></script>
{% endblock %}

templates/aloha/index.html
{% extends 'aloha/base.html' %}

{% block title %}MC3 Aloha Editor{% endblock %}

{% block content %}
    <div id="main" class="container">
        <div id="tech_warning" class="text-center row">
            <div class="col-lg-offset-2 col-lg-8 col-md-offset-0 col-md-12 col-sm-offset-0 col-sm-12 col-xs-offset-0 col-xs-12">
                <p class="text_bold red">Please note that this website is only compatible with the latest versions of FF / Chrome / Safari on Mac OS or FF / Chrome on Windows. It has not been tested on other combinations.
                </p>
            </div>
        </div>
        <div id="login_container" class="row">
            <div id="login_box" class="col-lg-offset-4 col-lg-4 col-md-offset-4 col-md-4 col-sm-offset-4 col-sm-4 col-xs-offset-2 col-xs-6">
                <form id="login" action="{% url 'aloha:login_page' %}" method="POST" enctype="multipart/form-data" class="form-horizontal" role="form">
                    {% csrf_token %}
                    <h4 class="text-center" id="login_heading">Login</h4>
                    <div class="form-group">
                        <label for="email" class="col-sm-1 control-label">
                            <i class="fa fa-envelope"></i>
                        </label>
                        <div class="col-sm-11">
                            <input type="text" class="form-control" id="email" name="email" placeholder="Email">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email" class="col-sm-1 control-label">
                            <i class="fa fa-lock"></i>
                        </label>
                        <div class="col-sm-11">
                            <input type="password" class="form-control" id="passwd" name="passwd" placeholder="Password">
                        </div>
                    </div>
                    <input type="hidden" name="next" value="{{ next }}"/>
                    <button id="login_btn" class="btn btn-large btn-primary" type="submit">Sign in</button>
                </form>
            </div>
        </div>
        <div class="row wrapper">
            <div class="col-lg-offset-4 col-lg-4 col-md-offset-4 col-md-4 col-sm-offset-4 col-sm-4 col-xs-offset-2 col-sm-6">
                <a href="{% url 'aloha:register' %}" id="register_link">Register</a>
            </div>
        </div>
    </div>
    <div id="tos_pp" class="container">
        <div class="row text-center">
            <div class="offset4 span4">
                <p>
                    Use of this site means that you agree to the
                    <a href="{% url 'aloha:tos' %}" target="_blank">Terms of Service</a> and
                    <a href="{% url 'aloha:privacy' %}" target="_blank">Privacy Policy</a>.
                </p>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_scripts %}
    <script type="text/javascript" src="{{STATIC_URL}}js/lib/jquery.validate.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/bindings/index.js"></script>
{% endblock %}

templates/aloha/register.html
{% extends 'aloha/base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-offset-3 col-lg-5 col-md-offset-3 col-md-5 col-sm-offset-3 col-sm-5 col-xs-offset-2 col-xs-6">
                <form id="signup" role="form" class="form-horizontal" method="post" action="{% url 'aloha:create_user' %}" enctype="multipart/form-data">
                    <h4>Sign Up For Access</h4>
                    {% csrf_token %}
                    {% if error %}
                        <label class="error red">{{ error }}</label>
                    {% endif %}
                    <div class="form-group">
                        <label for="fname" class="col-sm-2 control-label">
                            <i class="fa fa-user"></i>
                        </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="fname" name="fname" placeholder="First Name">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="lname" class="col-sm-2 control-label">
                            <i class="fa fa-user"></i>
                        </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="lname" name="lname" placeholder="Last Name">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email" class="col-sm-2 control-label">
                            <i class="fa fa-envelope"></i><sup>*</sup>
                        </label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="email" name="email" placeholder="Email">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="passwd" class="col-sm-2 control-label">
                            <i class="fa fa-lock"></i><sup>*</sup>
                        </label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" id="passwd" name="passwd" placeholder="Password">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="conpasswd" class="col-sm-2 control-label">
                            <i class="fa fa-lock"></i><sup>*</sup>
                        </label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" id="conpasswd" name="conpasswd" placeholder="Re-enter Password">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="tos" class="col-sm-10">I agree to this site's
                            <a href="{% url 'aloha:tos' %}" target="_blank">Terms of Service</a> and
                            <a href="{% url 'aloha:privacy' %}" target="_blank">Privacy Policy</a>.<sup>*</sup>
                        </label>
                        <div class="col-sm-2">
                            <input type="checkbox" id="tos" class="form-control" name="tos">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                           <button type="submit" class="btn btn-lg btn-success" >Create My Account</button>
                        </div>
                    </div>
                    <label><sup>*</sup> Required</label>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_scripts %}
    <script type="text/javascript" src="{{STATIC_URL}}js/lib/jquery.validate.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/bindings/register.js"></script>
{% endblock %}